# Generated by Django 5.1.dev20240126124152 on 2024-01-26 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cake_flavor', models.CharField(max_length=256)),
                ('filling_flavor', models.CharField(max_length=256)),
                ('slices', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.AddConstraint(
            model_name='cake',
            constraint=models.UniqueConstraint(condition=models.Q(('slices', 8)), fields=('cake_flavor', 'filling_flavor'), name='uniq_cake_flavor_filling_flavor'),
        ),
    ]
